baseURL = 'https://usdogu.github.io'
languageCode = 'en-us'
title = 'My Blog'
theme = "terminal"

[author]
  name = "Doğu Us"
  email = "uspro@disroot.org"

[params]
  author = "Doğu Us"
  title = "Doğu Us' Blog"
  themeColor = "red"
  centerTheme = true
  readingTime = true
  Toc = true

[languages]
  [languages.en]
    title = "Doğu Us' Blog"
    owner = "Doğu Us"
    keywords = "blog, technology, programming"
    [languages.en.params.logo]
      logoText = "USPRO"
      logoHomeLink = "/"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "rss"
        name = "RSS"
        url = "/index.xml"

