baseURL = 'https://usdogu.github.io'
languageCode = 'en-us'
title = 'My Blog'
theme = "terminal"

[author]
name = "Doğu Us"
email = "uspro@disroot.org"

[markup.goldmark.renderer]
  unsafe = true

[params]
centerTheme = true

[languages]
[languages.en]
[languages.en.menu]
[[languages.en.menu.main]]
idenfitifer = "RSS"
name = "RSS"
url = "/index.xml"
