on:
    push:
        paths:
            - "cv.typ"
jobs:
  compile_cv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile CV
        uses: lvignoli/typst-action@main
        with:
            source_file: |
                cv.typ

      - name: Move PDF to static
        run: |
          mv cv.pdf static/cv.pdf

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: "Update CV"

      - name: Dispatch CV compilation done event
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: cv-compilation-done
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}